apiVersion: v1
kind: Pod
metadata:
  namespace: dev
  name: nginx2
  labels:
    name: nginxPod
    type: proxyprod
spec:
  containers:
    - name: nginxcontainer
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
