kind: Service
apiVersion: v1
metadata:
  name: nodesrvc
spec:
  selector:
    server: web
  type: NodePort
  ports:
    - name: name-of-the-port
      port: 8080
      targetPort: 80
      nodePort: 31234
