apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    name: my-deployment
spec:
  replicas: 2 #2 pods. each pod having 2 containers specified below (i.e. nginx and ubuntu)
  selector:
    matchLabels:
      server: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        server: nginx
    spec:
      containers:
        - name: nginxcontainer
          image: nginx:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
        - name: server
          image: ubuntu:latest
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
          command: ["/bin/bash", "-c"] #needed to prevent ubuntu from crashing as it has nothing to do
          args:
            - sleep 600
