apiVersion: v1
kind: PersistentVolume
metadata:
  name: challenge-pv
spec:
  storageClassName: challenge
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: challenge-pvc
spec:
  storageClassName: challenge
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: storagedemo
  labels:
    name: pvcdemo
spec:
  containers:
    - name: democontainer
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
      volumeMounts:
        - name: challenge-volume # from volumes below
          mountPath: /var/www/html
  volumes:
    - name: challenge-volume
      persistentVolumeClaim:
        claimName: challenge-pvc #from pvc name above
